version: "2"
services:
    item-app:
        image: item-app:v1
        container_name: item-app
        # Set to always restart
        restart: always
        # Expose port 80 on host to 8080 on container
        ports:
            - 80:8080
        # Start only if item-db is successful
        depends_on:
            - item-db
    item-db:
        image: mongo:3
        container_name: item-db
        restart: always
        # use volume app-db to be mapped as /data/db on container
        volumes:
            - app-db:/data/db
volumes:
    app-db:
