version: 2.1
orbs:
    docker: circleci/docker@2.5.0
jobs:
    lint-dockerfile:
        executor: docker/machine
        working_directory: ~/workspace/repo
        steps:
            - checkout:
                  path: ~/workspace/repo
            - persist_to_workspace:
                  root: ~/workspace
                  paths:
                      - repo/*
            - docker/dockerlint:
                  dockerfile: ./Dockerfile
                  treat-warnings-as-errors: true
    build-app-shipping-service:
        executor: docker/machine
        working_directory: ~/workspace/repo
        steps:
            - attach_workspace:
                  at: ~/workspace
            - docker/build:
                  dockerfile: ./Dockerfile
                  image: cydnirn/shipping-service
                  tag: latest
                  registry: ghcr.io
            - run:
                  name: Login to ghcr.io
                  command: docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            - docker/push:
                  image: cydnirn/shipping-service
                  tag: latest
                  registry: ghcr.io

workflows:
    build-test-deploy:
        jobs:
            - lint-dockerfile
            - build-app-shipping-service:
                  requires:
                      - lint-dockerfile
